In [1]:
import numpy

In [5]:
# A função numpy.arrange() cria uma lista de quatro elementos, cujo primeiro é 0 e o último é 3. Esses elementos são
# manipulados pelas expressões abaixo e a saída é armazenada em c.

a = numpy.arange(4.0)
b = a * 23.4
c = b/(a+1)
c += 10
print(c)

[10.   21.7  25.6  27.55]


In [14]:
# Nesse trecho, a função define um arranjo entre 100 e 200, e em seguida define os elementos que serão exibidos
# através da lista select: caso o elemento dessa lista seja positivo, o código pegará o valor 100 e somará com
# esse elemento; caso seja negativo, pegará 200 e subtrairá o elemento.

arr = numpy.arange(100, 200)
select = [-30, 25, 50, 75, -5]
print(arr[select])

[170 125 150 175 195]


In [15]:
# Esse trecho de código está verificando quais números entre 10 e 20 são divisíveis por três.

arr = numpy.arange(10,20)
div_by_3 = arr%3 == 0
print(div_by_3)
print(arr[div_by_3])

[False False  True False False  True False False  True False]


In [22]:
# Esse trecho cria um arranjo entre 10 e 20 e, por meio da função reshape(5,2), o divide em cinco subarranjos de 2
# elementos cada.

arr = numpy.arange(10, 20) . reshape((5,2))
print(arr)

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
